Repository KTC-Security-Circle/SC-system-ai, pull requests merged in 2024-10, with the labels that each got.

#35 Create dependabot.yml
  .github/dependabot.yml
Labels: enhancement

#67 Fix/devcontainer command
  .devcontainer/devcontainer.json
  .devcontainer/scripts/post-attach.sh
  .devcontainer/scripts/post-create.sh
  requirements.txt
Labels: chore, fix

#77 update env file
  .env.sample
  requirements.txt
Labels: documentation, fix

#78 Fix/#68 workflows
  .github/dependabot.yml
  .github/labeler_branch.yml
  .github/workflows/assign_label.yml
  .github/workflows/create_release.yml
  .github/workflows/version_bump.yml
  .github/workflows/version_bump_major.yml
  .github/workflows/version_bump_minor.yml
Labels: chore, fix

#84 Merge branch 'feature/streaming-response'
  docs/agnet_invoke.md
  src/sc_system_ai/agents/classify_agent.py
  src/sc_system_ai/agents/dummy_agent.py
  src/sc_system_ai/agents/main_agent.py
  src/sc_system_ai/agents/streaming_agent.py
  src/sc_system_ai/template/agent.py
  src/sc_system_ai/template/calling_agent.py
  src/sc_system_ai/template/streaming_handler.py
  studies/streaming_resp.py
Labels: chore

#63 Feature/streaming response
  .devcontainer/devcontainer.json
  .gitignore
  docs/agnet_invoke.md
  poetry.lock
  pyproject.toml
  requirements.txt
  src/sc_system_ai/agents/classify_agent.py
  src/sc_system_ai/agents/dummy_agent.py
  src/sc_system_ai/agents/main_agent.py
  src/sc_system_ai/agents/streaming_agent.py
  src/sc_system_ai/agents/tools/__init__.py
  src/sc_system_ai/agents/tools/calling_dummy_agent.py
  src/sc_system_ai/agents/tools/classify_role.py
  src/sc_system_ai/agents/tools/magic_function.py
  src/sc_system_ai/agents/tools/search_duckduckgo.py
  src/sc_system_ai/agents/tools/search_school_data.py
  src/sc_system_ai/agents/tools/submit_official_absence.py
  src/sc_system_ai/logging_config.py
  src/sc_system_ai/main.py
  src/sc_system_ai/template/agent.py
  src/sc_system_ai/template/ai_settings.py
  src/sc_system_ai/template/azure_cosmos.py
  src/sc_system_ai/template/calling_agent.py
  src/sc_system_ai/template/streaming_handler.py
  src/sc_system_ai/template/system_prompt.py
  src/sc_system_ai/template/user_prompts.py
Labels: enhancement
