Repository KTC-Security-Circle/SC-system-ai, pull requests merged in 2024-11, with the labels that each got.

#87 add check action
  .github/workflows/check_code.yml
  poetry.lock
  pyproject.toml
  requirements.txt
  src/sc_system_ai/agents/classify_agent.py
  src/sc_system_ai/agents/tools/calling_dummy_agent.py
  src/sc_system_ai/agents/tools/classify_role.py
  src/sc_system_ai/agents/tools/submit_official_absence.py
  src/sc_system_ai/logging_config.py
  src/sc_system_ai/main.py
  src/sc_system_ai/template/agent.py
  src/sc_system_ai/template/azure_cosmos.py
  src/sc_system_ai/template/calling_agent.py
  src/sc_system_ai/template/streaming_handler.py
  src/sc_system_ai/template/system_prompt.py
  src/sc_system_ai/template/user_prompts.py
  studies/streaming_agent.py
Labels: fix

#101 Update check_code.yml
  .github/workflows/check_code.yml
Labels: chore, fix

#93 chat class update
  src/sc_system_ai/main.py
Labels: enhancement

#103 Create auto_merge.yml
  .github/workflows/auto_merge.yml
Labels: chore

#106 Update auto_merge.yml
  .github/workflows/auto_merge.yml
Labels: chore
